Fixed merge foreign to properly merge tag's class foreign key
ldbc/ldbc_snb_datagen_spark pull request #58
Opened 2018-01-18 17:08 UTC by ArnauPrat

2018-01-19 09:40 UTC, szarnyasg requested changes
A `Tag` can have multiple `TagClass`es. Its the `TAGCLASS_IS_SUBCLASS_OF_TAGCLASS("tagclass_isSubclassOf_tagclass")` file that should disappear and be merged to `TagClass`.

2018-01-19 09:43 UTC, ArnauPrat commented
OK. right, I got confused.

2018-01-19 14:48 UTC, szarnyasg approved these changes

2018-01-19 14:50 UTC, merged

2018-01-24 22:37 UTC, szarnyasg commented
As a followup, I also updated the [DATAGEN wiki](https://github.com/ldbc/ldbc_snb_datagen/wiki/Generated-CSV-MERGE-FOREIGN-Files/_compare/bdf81f53238715c14bb8271438237f54339cb997...021bb1d9a759cebb3cb6a6f1a3add0e76df3cdd2) and the [docs](https://github.com/ldbc/ldbc_snb_docs/commit/00ca1e2d411e256693bcdf1bd86ced55762ad1f3).